### ISSUE TITLE
Link places-101-android-kotlin#2 URL incorrect

### ISSUE THREAD

**Issue by huynhtuson** [googlemaps/codelab-places-101-android-kotlin#4]
Step 3
https://developers.google.com/codelabs/maps-platform/places-101-android-kotlin#2

git clone URL incorrect:
`https://github.com/googlemaps/codelab-places-101-android.git` 

maybe will : `https://github.com/googlecodelabs/maps-platform-101-android`? , I don't know

**Comment by wangela** [comment]
Apologies for this mixup! This has been fixed.
